{% set name = "conda-anaconda-telemetry" %}

package:
  name: {{ name|lower }}
  version: "{{ GIT_DESCRIBE_TAG }}.{{ GIT_BUILD_STR }}"

source:
  # git_url only captures committed code
  git_url: ../

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  noarch: python

requirements:
  build:
    - git  # for source/git_url above
  host:
    - python >=3.9
    - pip
    - hatchling >=1.12.2
    - hatch-vcs >=0.2.0
  run:
    - python >=3.9
    - conda >24.9.2

test:
  requires:
    - pip
    - conda >24.9.2
  commands:
    - conda --version
    - pip check
  imports:
    - conda_anaconda_telemetry
    - conda_anaconda_telemetry.hooks

about:
  home: https://github.com/anaconda/{{ name }}
  summary: Anaconda Telemetry conda plugin
  description: Anaconda Telemetry for conda adds helps us understand how conda is being used.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - travishathaway
    - jezdez
