{% set name = "conda-anaconda-telemetry" %}

package:
  name: {{ name|lower }}
  version: {{ GIT_DESCRIBE_TAG }}+{{ GIT_BUILD_STR }}

source:
  path: ../

build:
  number: 0
  script: {{ PYTHON }} -m pip install --no-build-isolation --no-deps .
  noarch: python

requirements:
  host:
    - pip
    - python
    - hatchling
    - hatch-vcs
  run:
    - python
    - conda-canary/label/dev::conda

test:
  requires:
    - conda-canary/label/dev::conda
    - pip
  commands:
    - conda --version
    - pip check
  imports:
    - conda_anaconda_telemetry
    - conda_anaconda_telemetry.hooks

about:
  home: https://github.com/anaconda/{{ name }}
  summary: Anaconda Telemetry conda plugin
  description: Anaconda Telemetry for conda adds helps us understand how conda is being used.
  license: BSD-3-Clause
  dev_url: https://github.com/anaconda/{{ name }}

extra:
  recipe-maintainers:
    - travishathaway
    - jezdez
