services:
  grafana:
    # Default username and password for Grafana are admin/admin
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ES_LOCAL_VERSION}
    container_name: ${ES_LOCAL_CONTAINER_NAME}
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 127.0.0.1:${ES_LOCAL_PORT}:9200
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ES_LOCAL_PASSWORD}
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.license.self_generated.type=basic
      - xpack.ml.use_auto_machine_memory_percent=true
      - ES_JAVA_OPTS=-Xms${ES_LOCAL_HEAP_INIT} -Xmx${ES_LOCAL_HEAP_MAX}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: [CMD-SHELL, 'curl --output /dev/null --silent --head --fail -u elastic:${ES_LOCAL_PASSWORD} http://elasticsearch:${ES_LOCAL_PORT}']
      interval: 5s
      timeout: 5s
      retries: 10

  otel_collector:
    image: otel/opentelemetry-collector-contrib:latest@sha256:631637f7b33668eda594011d5f173100a3fe245da7fa8dae0885b368da4d0a6e
    container_name: ${OTEL_LOCAL_CONTAINER_NAME}
    volumes:
      - ./otel-collector-config.yaml:/etc/otel/config.yaml
    ports:
      - 127.0.0.1:${OTEL_LOCAL_PORT}:4317
      - 127.0.0.1:${OTEL_LOCAL_ZPAGES_PORT}:55679
      - 127.0.0.1:${OTEL_LOCAL_HEALTH_CHECK_PORT}:13133
      - 127.0.0.1:${OTEL_LOCAL_PPROF_PORT}:1888
    command: --config /etc/otel/config.yaml

volumes:
  elasticsearch-data:
  grafana-data:
