receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

exporters:
  elasticsearch:
    endpoint: http://elasticsearch:9200
    traces_index: conda-anaconda-telemetry
    auth:
      authenticator: basicauth
  prometheus:
    endpoint: "otel_collector:8889"

extensions:
  health_check:
  pprof:
  zpages:
  basicauth:
    client_auth:
      username: elastic
      password: password

processors:
  batch:

service:
  extensions: [basicauth, health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [elasticsearch]
      processors: [batch]
    logs:
      receivers: [otlp]
      exporters: [elasticsearch]
      processors: [batch]
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
      processors: [batch]
